### ISSUE TITLE
Перестали добавляться устройства

### ISSUE THREAD

**Issue by konditerov** [altfoxie/ha-sberdevices#10]
Добрый день, это было единственное приложение для HA, где можно было прокинуть лампы сбера в Яндекс и Homekit.

Сейчас перестали добавляться устройства (свет)

Регистратор: homeassistant.components.light
Источник: helpers/entity_platform.py:366
интеграция: Освещение (документация, проблемы)
Первое сообщение: 17:02:25 (4 сообщений)
Последнее сообщение: 17:03:34
`
Error while setting up sberdevices platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sberdevices/light.py", line 44, in async_setup_entry
    await home.update_devices_cache()
  File "/config/custom_components/sberdevices/api.py", line 136, in update_devices_cache
    self._devices = extract_devices(await self.get_device_tree())
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 132, in get_device_tree
    return (await self.request("GET", "/device_groups/tree"))["result"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 116, in request
    await self.update_token()
  File "/config/custom_components/sberdevices/api.py", line 109, in update_token
    token = await self._sber.fetch_home_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 93, in fetch_home_token
    ).json()["token"]
      ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by YA012345678** [comment]
У вас только новые устройства не добавить? 
У меня отвалились все-все, уже работавшие ранее - **Этот объект больше не предоставляется интеграцией sberdevices**

**Comment by rozzario76** [comment]
+1 тоже все отвалилось. По новой не добавляется.

**Comment by konditerov** [comment]
> У вас только новые устройства не добавить? У меня отвалились все-все, уже работавшие ранее - **Этот объект больше не предоставляется интеграцией sberdevices**
Нет, у меня перестали работать, но, т.к. я ночью это обновил всё что можно было обновить, то и списал это на несовместимость версий. После целого дня поисков бекапа - в итоге просто переустановил и восстановил.

**Comment by altfoxie** [comment]
Исправлено в v1.0.2

**Comment by konditerov** [comment]
@altfoxie 
Прошу прощения, а можно обновлять следующие компоненты?
<img width="342" alt="Снимок экрана 2024-08-28 в 21 43 43" src="https://github.com/user-attachments/assets/31481c1f-e27d-4943-b289-cb6b8fb8ff55">

**Comment by altfoxie** [comment]
@konditerov обновление этих компонентов не должно затронуть мою интеграцию, но решение только за тобой  ¯\_(ツ)_/¯
