### ISSUE TITLE
После перезагрузки системы, устройства отваливаются

### ISSUE THREAD

**Issue by GeneriumMadness** [altfoxie/ha-sberdevices#12]
При перезагрузке системы HA либо всего сервера в целом, все лампы отваливаются от интеграции и не поднимаются, пока снова не авторизоваться.
На экране каждой лампы написано 
`Этот объект больше не предоставляется интеграцией sberdevices. Вы можете удалить его на вкладке "Настройки", если он больше не будет использоваться.`

**Comment by TohaRG2** [comment]
Отвалились сбер лампочки и сберлента, при попытке повторной авторизации

2024-11-30 23:27:18.893 ERROR (MainThread) [homeassistant.components.light] Error while setting up sberdevices platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sberdevices/light.py", line 45, in async_setup_entry
    await home.update_devices_cache()
  File "/config/custom_components/sberdevices/api.py", line 140, in update_devices_cache
    self._devices = extract_devices(await self.get_device_tree())
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 136, in get_device_tree
    return (await self.request("GET", "/device_groups/tree"))["result"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 120, in request
    await self.update_token()
  File "/config/custom_components/sberdevices/api.py", line 112, in update_token
    token = await self._sber.fetch_home_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 90, in fetch_home_token
    await self._oauth_client.get(
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1814, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 84, in request
    raise MissingTokenError()
authlib.integrations.base_client.errors.MissingTokenError: missing_token:

**Comment by taziy** [comment]
Таже проблема 😏

**Comment by kostiaprofrom** [comment]
Есть идеи как пофиксить?

**Comment by eXist-FraGGer** [comment]
https://sberdevices.ru/help/smarthome/another-platform/compatible/#direct-list

Они же заявляют что работает с Z2M, полагаю большинство устройств можно на прямую подключить в HA?
