### ISSUE TITLE
Нет устройств

### ISSUE THREAD

**Issue by Chepaeff** [altfoxie/ha-sberdevices#2]
**НА_version: 2024.1.5**

При добавлении интеграции, не отображаются устройства.

![error](https://github.com/altfoxie/ha-sberdevices/assets/6481193/7c3777ac-36b6-4c6d-a9c9-1a0bdfe6911a)

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:360
Integration: Освещение (documentation, issues)
First occurred: 12:34:44 (10 occurrences)
Last logged: 22:39:56

**Error while setting up sberdevices platform for light**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/sberdevices/light.py", line 37, in async_setup_entry
    await home.update_devices_cache()
  File "/config/custom_components/sberdevices/api.py", line 93, in update_devices_cache
    self._devices = extract_devices(await self.get_device_tree())
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 89, in get_device_tree
    return (await self.request("GET", "/device_groups/tree"))["result"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 73, in request
    await self.update_token()
  File "/config/custom_components/sberdevices/api.py", line 66, in update_token
    token = await self._sber.fetch_home_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sberdevices/api.py", line 49, in fetch_home_token
    await self._oauth_client.get("https://mp.aihome.dev/v11/smarthome/token")
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1786, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 84, in request
    raise MissingTokenError()
authlib.integrations.base_client.errors.MissingTokenError: missing_token:

**Comment by Chepaeff** [comment]
С третьей попытки устройство появилось.

![error](https://github.com/altfoxie/ha-sberdevices/assets/6481193/c7a66dcc-778b-4f53-a1a5-678c018dddfd)
